### ISSUE TITLE
Verzoek tot bijwerken voor Stembureaus ODS v1.6

### ISSUE THREAD

**Issue by Hilbrand** [VNG-Realisatie/ODS-Stembureaus#4]
Voor Europese Parlementsverkiezingen 2024 is er een nieuwe versie Stembureaus ODS v1.6 beschikbaar op https://waarismijnstemlokaal.nl/data. Komt de nieuwe versie nog hier?

**Comment by siccovansas** [comment]
@baksand heeft de nieuwe standaard ontvangen, dus deze wordt hier hopelijk binnenkort ook gepubliceerd.
